import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image'
import '../node_modules/font-awesome/css/font-awesome.min.css';
import { useState, useEffect } from 'react';

export default function Layout({ children }) {
    let user = null;

    if(typeof window !== 'undefined'){
        user = JSON.parse(window.localStorage.getItem("user"));
    }

    return (
        <div>
            <Head>
                <title>Cube - NEXT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={"flex flex-row w-full h-full"}>
                <div className="h-screen bg-purple-cube text-white pb-6 min-w-30 w-30 md:w-80 shadow-3xl">
                    <div className="flex flex-col w-full h-full">
                        {/* <p className='font-bold text-center text-xl tracking-widest py-4 pb-12'>CUBE</p> */}
                        <div className='w-full h-40 bg-gray-900 mb-8 py-4 px-2'>
                            <div className='flex flex-col h-full justify-center'>
                                <div className='flex'>
                                    <div className='image-container h-14 w-14'>
                                        <Image src="/img/background-login.jpg" layout="fill" className='rounded-full hover:opacity-70 cursor-pointer image' />
                                    </div>
                                    {/* <Image width={45}  height={45} src="/img/background-login.jpg" className='rounded-full hover:opacity-70 cursor-pointer' /> */}
                                    <div className='hidden md:block'>
                                        <Link href={"/profile"}>
                                            <p className='px-4 hidden md:block whitespace-nowrap cursor-pointer hover:underline hover:text-grey transition'>{user != null ? user.firstname + " " + user.lastname : ''}</p>
                                        </Link>
                                        <Link href={"/profile"}>
                                            <p className='px-4 hidden md:block whitespace-nowrapwhitespace-nowrap text-xs text-gray-300 cursor-pointer hover:underline hover:text-grey transition'>{user != null ? user.tag : ''}</p>
                                        </Link>
                                    </div>
                                </div>
                                <div className='hidden md:flex w-full justify-between px-2 mt-4 text-xs text-gray-300 whitespace-nowrap'>
                                    <p className='hover:text-gray-100 cursor-pointer'>104 relations</p>
                                </div>
                            </div>
                        </div>
                        <div className="flex flex-col">
                            <Link href="/">
                                <div className="flex cursor-pointer text-xl mb-12 hover:text-gray-400">
                                    <i className="my-auto mx-6 w-full text-center md:w-6 fa fa-hashtag" aria-hidden="true"></i>
                                    <div className='w-full my-auto text-base tracking-widest hidden md:block my-auto whitespace-nowrap'>Fil d'actualité</div>
                                </div>
                            </Link>
                            <Link href="/favorites">
                                <div className="flex cursor-pointer text-xl mb-12 hover:text-gray-400">
                                    <i className="my-auto mx-6 w-full text-center md:w-6 fa fa-heart"></i>
                                    <div className='w-full my-auto text-base tracking-widest hidden md:block my-auto whitespace-nowrap'>Favoris</div>
                                </div>
                            </Link>
                            <Link href="/relations">
                                <div className="flex cursor-pointer text-xl mb-12 hover:text-gray-400">
                                    <i className="my-auto mx-6 w-full text-center md:w-6 fa fa-users"></i>
                                    <div className='w-full my-auto text-base tracking-widest hidden md:block my-auto whitespace-nowrap'>Amis</div>
                                </div>
                            </Link>
                            <Link href="/resources">
                                <div className="flex cursor-pointer text-xl mb-12 hover:text-gray-400">
                                    <i className="my-auto mx-6 w-full text-center md:w-6 fa fa-plus-square"></i>
                                    <div className='w-full my-auto text-base tracking-widest hidden md:block my-auto whitespace-nowrap'>Ressources</div>
                                </div>
                            </Link>
                            <Link href="/profile">
                                <div className="flex cursor-pointer text-xl mb-12 hover:text-gray-400">
                                    <i className="my-auto mx-6 w-full text-center md:w-6 fa fa-user"></i>
                                    <div className='w-full my-auto text-base tracking-widest hidden md:block my-auto whitespace-nowrap'>Profil</div>
                                </div>
                            </Link>

                        </div>
                        <div className='mt-auto'>
                            <Link href="/parameters">
                                <div className="flex cursor-pointer text-2xl mb-8 hover:text-gray-400">
                                    <i className="my-auto mx-6 w-full text-center md:w-6 fa fa-gear"></i>
                                    <div className='w-full my-auto text-base tracking-widest hidden md:block my-auto whitespace-nowrap'>Paramètres</div>
                                </div>
                            </Link>
                        </div>
                    </div>
                </div>
                <main className="grow px-4 bg-gray-100 h-screen overflow-auto">
                    {children}
                </main>
            </div>
        </div>
    )
}
